version: "3"

services:
  mine:
    build:
      context: .
    container_name: >
      minecore
    ports:
      - "8000:8000"
    volumes:
      - ./minecore:/minecore
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
