version: "3"

services:
  mine:
    build:
      context: .
    container_name: minecore
    ports:
      - "8000:8000"
    volumes:
      - ./minecore:/minecore
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=mine
      - DB_USER=postgres
      - DB_PASS=nepal123
    depends_on:
      - db
  
  db:
    container_name: minedb
    image: postgres:10-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=mine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nepal123



