# Generated by Django 2.2.3 on 2019-07-11 16:43

import coreproductmodel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coremodels', '0002_auto_20190711_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField()),
                ('major_catalog', models.CharField(blank=True, choices=[('sig', 'Signature Products'), ('ant', 'Antiques'), ('A&C', 'Arts and Crafts'), ('BeR', 'Better Replacement'), ('cul', 'Cultural'), ('dec', 'Decor'), ('G&J', 'Gems and Jewellery'), ('hrb', 'Herbals'), ('NaF', 'Natural Fabrics'), ('let', 'Leather'), ('sou', 'Souvenir'), ('mus', 'Musical Instruments')], max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalog',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input product name', max_length=255, verbose_name='Product Name')),
                ('materialDescription', models.TextField(help_text='Input product material description', verbose_name='Product Description')),
                ('product_image', models.ImageField(blank=True, help_text='Input products image', null=True, upload_to=coreproductmodel.models.upload_productimage_path, verbose_name='Product Image')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='A products price', max_digits=5)),
                ('weight', models.FloatField(help_text='A products weight')),
                ('size', models.CharField(blank=True, help_text='A products Size', max_length=255, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='A product is available in Inventory')),
                ('has_offer_value', models.BooleanField(default=False, help_text='A product is on sale or has an offer')),
                ('catalog_category', models.ForeignKey(help_text='Product associated Category defined on the Catalog', on_delete=django.db.models.deletion.CASCADE, to='coreproductmodel.Catalog', verbose_name='Category')),
                ('color', models.ManyToManyField(help_text=' A products color', to='coremodels.RelatedProductColors')),
                ('relatedType', models.ManyToManyField(help_text=' Input related product type', to='coremodels.RelatedProductTypes', verbose_name='Related Product Type')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
