# Generated by Django 2.2.3 on 2019-07-11 17:22

import coreproductmodel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreproductmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=coreproductmodel.models.upload_productimage_path)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coreproductmodel.Products')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
