# Generated by Django 2.2.3 on 2019-07-11 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreproductmodel', '0002_productimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('usage_limit', models.IntegerField(default=0)),
                ('expiring_date', models.DateTimeField()),
                ('code_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreproductmodel.Products')),
            ],
            options={
                'verbose_name_plural': 'PromoCodes',
            },
        ),
    ]
