# Generated by Django 2.2.3 on 2019-07-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreproductmodel', '0004_auto_20190711_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='relatedType',
            field=models.ManyToManyField(help_text='Input related product type', to='coremodels.RelatedProductTypes', verbose_name='Related Product Type'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
