# Generated by Django 2.2.3 on 2019-07-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedproductcolors',
            name='name',
            field=models.CharField(help_text='Products Colors', max_length=100, unique=True, verbose_name='Color Name'),
        ),
        migrations.AlterField(
            model_name='relatedproducttypes',
            name='name',
            field=models.CharField(help_text='Products related type. eg: Kitchenware', max_length=255, unique=True),
        ),
    ]
